Removing "path" param, causing problems with Ubuntu's 3.3.8-1ubuntu6.3 package
Was seeing this before:
proxy# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for proxy
Info: Applying configuration version '1444072077'
Error: Execution of '/usr/sbin/update-rc.d squid3 defaults' returned 1: update-rc.d: /etc/init.d/squid3: file does not exist
Error: /Stage[main]/Squid3/Service[squid3_service]/enable: change from false to true failed: Execution of '/usr/sbin/update-rc.d squid3 defaults' returned 1: update-rc.d: /etc/init.d/squid3: file does not exist
Notice: Finished catalog run in 11.45 seconds
proxy#